Controllers/OgrenciController.cs
using System.Net.Http.Headers;
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualBasic;

namespace efcoreApp.Controllers
{
    public class OgrenciController:Controller
    {
        // DataContext sınıfı, veritabanı bağlamınızı temsil eder ve Entity Framework Core tarafından kullanılır.
        private readonly DataContext _context;
        // Controller sınıfının yapıcı metodu. Dependency Injection yoluyla DataContext nesnesini alır.
        public OgrenciController (DataContext context)
        {
            // Alınan DataContext nesnesi, özel alana atanır.
            _context = context;
        }
        public async Task<IActionResult> Index() //async Task asekron gönderimlerde kullanılıyor
        {            
            return View(await _context.Ogrenciler.ToListAsync()); // await asekron metodun da olması gereken bekletme kodu
        }
        public IActionResult Create(){
             // Bu metod çağrıldığında, 'Create' adında bir View döndürülür.
             // MVC, 'Create' adında bir .cshtml dosyasını Views klasöründe arar.
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create (Ogrenci model)
        {
            _context.Ogrenciler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }
         [HttpGet]
        public async Task<IActionResult> Edit(int? id) //Edit Butonu
        {
            if(id==null)
            {
                return NotFound();
            }
            var ogr = await _context
            .Ogrenciler
            .Include(o => o.KursKayitlari)
            .ThenInclude(o => o.Kurs)
            .FirstOrDefaultAsync(o => o.OgrenciId==id); 
            // Alternatif Arama Yöntemi
            // var ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o => o.OgrenciId == id);


            if (ogr == null)
            {
                return NotFound();
            }
            return View(ogr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Güvenlik önlemi şifreli bir şekilde verinin doğru yerden gelip gelmediğine bakar
        public async Task<IActionResult> Edit(int id,Ogrenci model)
        {
            if(id != model.OgrenciId) //gönderiler Id ile Veritabanındaki Id aynı değil ise
            {
                return NotFound(); // 404 hata sayfasına yönlendir.
            }
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync(); //Veri tabanına aktarmak.
                }
                catch(DbUpdateConcurrencyException)
                {
                    //Any herhangi bir demek. Bir yada daha fazla kayıt varmı sorgusunda kullanılıyor.
                    if(!_context.Ogrenciler.Any(o => o.OgrenciId == model.OgrenciId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw; //kaldığın yerden devam et.
                    }
                }
                return RedirectToAction("Index"); //Güncellemeyi Geriye gönder.
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ogr =await _context.Ogrenciler.FindAsync(id);
            if(ogr == null)
            {
                return NotFound();
            }
            return View(ogr);
        }
        [HttpPost]
        public async Task<IActionResult> Delete ([FromForm]int id)
        {
            var ogrenci = await _context.Ogrenciler.FindAsync(id);
            if(ogrenci==null)
            {
                return NotFound();
            }
            _context.Ogrenciler.Remove(ogrenci);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Ogrenci/Create.cshtml
@model Ogrenci
<h2>Öğrenci Ekle</h2>
<hr>
<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label">SoyAdı </label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">E-Posta Adresi</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon Numarası</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-secondary">Kaydet</button>
</form>

Views/Ogrenci/Delete.cshtml
@model Ogrenci

<p>
   <b>@Model.OgrenciAd @Model.OgrenciSoyad </b> isimli öğrenciyi silmek istiyor musunuz?
   <form asp-action="Delete" method="post">
    <input type="hidden" name="id" value="@Model.OgrenciId">
    <button type="submit" class="btn btn-danger">Sil</button>
    <a asp-action="Index" class="btn btn-primary">Vazgeç</a>
   </form>
</p>

Views/Ogrenci/Edit.cshtml
@model Ogrenci

<h2>Öğrenci Düzenle</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Ogrenci" asp-action="Edit" method="post">
    <input type="hidden" asp-for="OgrenciId">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label">SoyAdı </label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">E-Posta Adresi</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon Numarası</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button class="btn btn-secondary">Kaydet</button>
</form>
    </div>
    <div class="col-4">
        <h4>Kurslar</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.KursKayitlari)
            {
                <li>@item.Kurs.Baslik</li>
            }
        </ul>
    </div>

</div>

Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>

    <h2 class="mb-3">Öğrecilerimiz</h2>
    <a asp-conroller="Ogrenci" asp-action="Create" class="btn btn-primary btn-sm">Yeni Öğrenci Ekle</a>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <!-- DisplayNameFor Listenin adını alırken kullanıyor -->
                <th style="width: 150px; ">@Html.DisplayNameFor(m => m.OgrenciId)</th> 
                <th>@Html.DisplayNameFor(m => m.OgrenciAd)</th>
                <th style="width: 150px; ">@Html.DisplayNameFor(m => m.OgrenciSoyad)</th>
            </tr>
        </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <!-- DisplayFor Listenin İçeriğini almak için kullanıyor -->
            <td>@Html.DisplayFor(modelItem => item.OgrenciId)</td>
            <td>@Html.DisplayFor(modelItem => item.OgrenciAd)</td>
            <td>@Html.DisplayFor(modelItem => item.OgrenciSoyad)</td>
            <td>
                <a asp-controller="Ogrenci" asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-primary">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-danger">Delete</a>
            </td>

        </tr>
        }

    </tbody>
</table>