Controllers/OgretmenController.cs
using System.Net.Http.Headers;
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualBasic;

namespace efcoreApp.Controllers
{
    public class OgretmenController:Controller
    {
        private readonly DataContext _context;
        public OgretmenController (DataContext context)
        {
            // Alınan DataContext nesnesi, özel alana atanır.
            _context = context;
        }
        public async Task<IActionResult> Index() //async Task asekron gönderimlerde kullanılıyor
        {            
            return View(await _context.Ogretmenler.ToListAsync()); // await asekron metodun da olması gereken bekletme kodu
        }
         public IActionResult Create(){
             // Bu metod çağrıldığında, 'Create' adında bir View döndürülür.
             // MVC, 'Create' adında bir .cshtml dosyasını Views klasöründe arar.
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create (Ogretmen model)
        {
            _context.Ogretmenler.Add(model);
            // model.BaslamaTarihi=DateTime.Now;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        //---------------------------------------------Edit ve Delete
         [HttpGet]
        public async Task<IActionResult> Edit(int? id) //Edit Butonu
        {
            if(id==null)
            {
                return NotFound();
            }
            var entity = await _context
            .Ogretmenler            
            .FirstOrDefaultAsync(o => o.OgretmenId==id); 
            // Alternatif Arama Yöntemi
            // var ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o => o.OgrenciId == id);


            if (entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Güvenlik önlemi şifreli bir şekilde verinin doğru yerden gelip gelmediğine bakar
        public async Task<IActionResult> Edit(int id,Ogretmen model)
        {
            if(id != model.OgretmenId) //gönderiler Id ile Veritabanındaki Id aynı değil ise
            {
                return NotFound(); // 404 hata sayfasına yönlendir.
            }
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync(); //Veri tabanına aktarmak.
                }
                catch(DbUpdateConcurrencyException)
                {
                    //Any herhangi bir demek. Bir yada daha fazla kayıt varmı sorgusunda kullanılıyor.
                    if(!_context.Ogretmenler.Any(o => o.OgretmenId == model.OgretmenId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw; //kaldığın yerden devam et.
                    }
                }
                return RedirectToAction("Index"); //Güncellemeyi Geriye gönder.
            } 
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity =await _context.Ogretmenler.FindAsync(id);
            if(entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }
        [HttpPost]
        public async Task<IActionResult> Delete ([FromForm]int id)
        {
            var ogretmen = await _context.Ogretmenler.FindAsync(id);
            if(ogretmen==null)
            {
                return NotFound();
            }
            _context.Ogretmenler.Remove(ogretmen);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        //---------------------------------------------Edit ve Delete Son

    }    
}

Views/Ogretmen/Create.cshtml
@model Ogretmen
<h2>*Öğretmen Ekle</h2>
<hr>
<form asp-controller="Ogretmen" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
        <input asp-for="Ad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="SoyAd" class="form-label">SoyAdı </label>
        <input asp-for="SoyAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">E-Posta Adresi</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon Numarası</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="BaslamaTarihi" class="form-label">Baslama Tarihi</label>
        <input asp-for="BaslamaTarihi" class="form-control">
    </div>
    <button type="submit" class="btn btn-success">Kaydet</button>
</form>

Views/Ogretmen/Delete.cshtml
@model Ogretmen

<p>
   <b>@Model.Ad @Model.SoyAd </b> isimli öğretmeni silmek istiyor musunuz?
   <form asp-action="Delete" method="post">
    <input type="hidden" name="id" value="@Model.OgretmenId">
    <button type="submit" class="btn btn-danger">Sil</button>
    <a asp-action="Index" class="btn btn-primary">Vazgeç</a>
   </form>
</p>

Views/Ogretmen/Edit.cshtml
@model Ogretmen

<h2>Öğretmen Düzenle</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Ogretmen" asp-action="Edit" method="post">
            <input type="hidden" asp-for="OgretmenId">
            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
                <input asp-for="Ad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="SoyAd" class="form-label">SoyAdı </label>
                <input asp-for="SoyAd" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Eposta" class="form-label">E-Posta Adresi</label>
                <input asp-for="Eposta" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon Numarası</label>
                <input asp-for="Telefon" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="BaslamaTarihi" class="form-label">Baslama Tarihi</label>
                <input asp-for="BaslamaTarihi" class="form-control">
            </div>
            <button class="btn btn-success">Kaydet</button>
        </form>
    </div>
</div>

Views/Ogretmen/Index.cshtml
@model IEnumerable<Ogretmen>

    <h2 class="mb-3">Öğretmenlerimiz</h2>
    <a asp-conroller="Ogretmen" asp-action="Create" class="btn btn-primary btn-sm">Yeni Öğretmen Ekle</a>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <!-- DisplayNameFor Listenin adını alırken kullanıyor -->
                <th style="width: 150px; ">@Html.DisplayNameFor(m => m.OgretmenId)</th> 
                <th>@Html.DisplayNameFor(m => m.Ad)</th>
                <th style="width: 150px; ">@Html.DisplayNameFor(m => m.SoyAd)</th>
                <th style="width: 150px; ">@Html.DisplayNameFor(m => m.BaslamaTarihi)</th>

            </tr>
        </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <!-- DisplayFor Listenin İçeriğini almak için kullanıyor -->
            <td>@Html.DisplayFor(modelItem => item.OgretmenId)</td>
            <td>@Html.DisplayFor(modelItem => item.Ad)</td>
            <td>@Html.DisplayFor(modelItem => item.SoyAd)</td>
            <td>@Html.DisplayFor(modelItem => item.BaslamaTarihi)</td>
            
            <td>
                <a asp-controller="Ogretmen" asp-action="Edit" asp-route-id="@item.OgretmenId" class="btn btn-sm btn-primary">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.OgretmenId" class="btn btn-sm btn-danger">Delete</a>
            </td>

        </tr>
        }

    </tbody>
</table>