Controllers/KursController.cs
using efcoreApp.Data;
using efcoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class KursController:Controller
    {
        private readonly DataContext _context;
        public KursController (DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var kurslar = await _context.Kurslar
            .Include(k =>k.Ogretmen)
            .ToListAsync();
            return View(kurslar);
        }

        public async Task<IActionResult> Create(){
            ViewBag.Ogretmenler =new SelectList( await _context.Ogretmenler.ToListAsync(), "OgretmenId","AdSoyad");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create (KursViewModel model)
        {
            if(ModelState.IsValid)
            {
                _context.Kurslar.Add(new Kurs(){KursId=model.KursId, Baslik=model.Baslik, OgretmenId=model.OgretmenId});
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
            }
            
            ViewBag.Ogretmenler =new SelectList( await _context.Ogretmenler.ToListAsync(), "OgretmenId","AdSoyad");
            return View(model);
        }

        //------------------------------------------------------Edit Get - Post Kısmı
         [HttpGet]
        public async Task<IActionResult> Edit(int? id) //Edit Butonu
        {
            if(id==null)
            {
                return NotFound();
            }
            var krs = await _context
            .Kurslar
            .Include(k => k.kurskayit)
            .ThenInclude(k => k.Ogrenci)
            .Select(k => new KursViewModel{
                KursId=k.KursId,
                Baslik=k.Baslik,
                OgretmenId=k.OgretmenId,
                kurskayit=k.kurskayit
            })
            .FirstOrDefaultAsync(k => k.KursId == id); 
            // Alternatif Arama Yöntemi
            // var ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o => o.OgrenciId == id);


            if (krs == null)
            {
                return NotFound();
            }

            ViewBag.Ogretmenler =new SelectList( await _context.Ogretmenler.ToListAsync(), "OgretmenId","AdSoyad");

            return View(krs);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Güvenlik önlemi şifreli bir şekilde verinin doğru yerden gelip gelmediğine bakar
        public async Task<IActionResult> Edit(int id,KursViewModel model)
        {
            if(id != model.KursId) //gönderiler Id ile Veritabanındaki Id aynı değil ise
            {
                return NotFound(); // 404 hata sayfasına yönlendir.
            }
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(new Kurs(){KursId=model.KursId, Baslik=model.Baslik, OgretmenId=model.OgretmenId});
                    await _context.SaveChangesAsync(); //Veri tabanına aktarmak.
                }
                catch(DbUpdateConcurrencyException)
                {
                    //Any herhangi bir demek. Bir yada daha fazla kayıt varmı sorgusunda kullanılıyor.
                    if(!_context.Ogrenciler.Any(o => o.OgrenciId == model.KursId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw; //kaldığın yerden devam et.
                    }
                }
                return RedirectToAction("Index"); //Güncellemeyi Geriye gönder.
            }
            ViewBag.Ogretmenler =new SelectList( await _context.Ogretmenler.ToListAsync(), "OgretmenId","AdSoyad");

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var krs =await _context.Kurslar.FindAsync(id);
            if(krs == null)
            {
                return NotFound();
            }
            return View(krs);
        }

        //-------------------------------------------------------------Edit Son

        //-------------------------------------------------------------Delete
        [HttpPost]
        public async Task<IActionResult> Delete ([FromForm]int id)
        {
            var krs = await _context.Kurslar.FindAsync(id);
            if(krs==null)
            {
                return NotFound();
            }
            _context.Kurslar.Remove(krs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        //-------------------------------------------------------------Delete Son

    }
}

Controllers/KursKayitController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace efcoreApp.Controllers
{
    public class KursKayitController:Controller
    {
        private readonly DataContext _context;
        public KursKayitController(DataContext context)
        {
            _context= context;
        }

        public async Task<IActionResult> Index()
        {
            var kursKayitleri = await _context
                        .KursKayitleri
                        .Include(x => x.Ogrenci)
                        .Include(x => x.Kurs)
                        .ToListAsync();
            return View(kursKayitleri);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler =new SelectList( await _context.Ogrenciler.ToListAsync(), "OgrenciId","AdSoyad");
            ViewBag.Kurslar =new SelectList( await _context.Kurslar.ToListAsync(), "KursId","Baslik");
            return View();
        }


        [HttpPost]       
        [ValidateAntiForgeryToken] 
        public async Task<IActionResult> Create(KursKayit model)
        {
            model.KayitTarihi=DateTime.Now;
            _context.KursKayitleri.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/KursKayit/Create.cshtml
@model KursKayit
<h2>Kurs Kaydı Ekle</h2>
<hr>
<form asp-controller="KursKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci adı</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs </label>
        <select asp-for="KursId" asp-items="ViewBag.Kurslar" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>
    
    <button type="submit" class="btn btn-success">Kaydet</button>
</form>

Views/KursKayit/Index.cshtml
@model IEnumerable<KursKayit>

<h2 class="mb-3">Kurs Kayıtları</h2>
<p>Öğrencilerimizi mevcut kurslara kayıt yapabilirsiniz.</p>
<a asp-conroller="KursKayit" asp-action="Create" class="btn btn-primary btn-sm">Yeni Kayıt</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m =>m.KursKayitId) </th>
            <th>@Html.DisplayNameFor(m =>m.Ogrenci.OgrenciId) </th>
            <th>@Html.DisplayNameFor(m =>m.Kurs.Baslik) </th>
            <th style="width: 150px;"></th>


        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.KursKayitId)</td>
                <td>@Html.DisplayFor(modelItem => item.Ogrenci.AdSoyad)</td>
                <td>@Html.DisplayFor(modelItem => item.Kurs.Baslik)</td>
                <td>
                    <a asp-controller="Kurs" asp-action="Edit" asp-route-id="@item.KursId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.KursId" class="btn btn-sm btn-danger">Delete</a>
                </td>


            </tr>
        }
    </tbody>
</table>